name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build test Docker image
      run: docker build . --file Dockerfile --target test --tag autotest-example:test
    - name: Run tests
      run: docker run autotest-example:test
